name: Release

on:
  create:
    tags:
      - v*.*.*

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:

      - name: Check event ref type
        run: |
          export CREATE_EVENT_REF_TYPE=$(jq --raw-output .ref_type "$GITHUB_EVENT_PATH")
          if [ "$CREATE_EVENT_REF_TYPE" != "tag" ]; then echo "ref_type is not a tag: ${CREATE_EVENT_REF_TYPE}" && exit 78; fi

      - uses: actions/checkout@master

      - name: Set up Go 1.13
        uses: actions/setup-go@v1
        with:
          version: 1.13
        id: go

      - name: Set up Node
        uses: actions/setup-node@v1
        with:
          node-version: '10.x'
        id: node

      - name: Build assets
        working-directory: ./frontend
        run: yarn && yarn build

      - name: Install, Generate, Build
        working-directory: ./backend
        run: |
          export PATH=$PATH:$(go env GOPATH)/bin
          GO111MODULE=off go get github.com/shogo82148/assets-life
          make gen
          make build
      - name: Publish release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          export PATH=$PATH:$(go env GOPATH)/bin
          export TAGNAME=$(jq --raw-output .ref "$GITHUB_EVENT_PATH")
          GO111MODULE=off go get github.com/tcnksm/ghr
          ghr -n ${TAGNAME} -b "Release ${TAGNAME}" -draft ${TAGNAME} pkg/
